//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 BD.Common8.SourceGenerator.ResX.Test.Helpers.ResXHelper 生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable IDE0079 // 请删除不必要的忽略
#pragma warning disable IDE0130 // 命名空间与文件夹结构不匹配
namespace BD.SteamClient8.Resources;
#pragma warning restore IDE0079 // 请删除不必要的忽略

[ResXGeneratedCode(@"..\..\..\res\i18n\BD.SteamClient8.Primitives.resx", version: 1)]
public partial class Strings { }
